layout_spectrum: 0.6834563711102093
typography_spectrum: 0.2828880849425303
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.19672279349251623
  lightness: 0.44102130998165745
  saturation: 0.9022827292663405
  rhythmicContrast: 0.9794722743851529
name: Impossible Girl's Kissable Skin
analytics:
  facebook: '1788863521350364'
  google: UA-78600613-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Contact me to order
    url: 'mailto:silvatungfox@gmail.com'
title: Kissable Skin
description: All natural healing salve
author:
  name: Maurine L Dodge
  url: 'http://maurinedodge.photo/'
  email: silvatungfox@gmail.com
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07cf496-0ac8-4929-a2c5-0f35fc5292f5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07cf496-0ac8-4929-a2c5-0f35fc5292f5.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
